config/routes.rb
Rails.application.routes.draw do

  root 'pages#dashboard'

  get '/secrets' => 'secrets#index', as: :secrets
  post '/secrets' => 'secrets#create', as: :secret

   get 'login' => 'session#new', as: :login
   post 'auth' => 'session#create', as: :auth
   get 'signup' => 'users#new', as: :signup
   post 'signup' => 'users#create', as: :user
   delete 'logout' => 'session#destroy', as: :logout

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController


  def dashboard
    @secrets = JSON.parse Http.get("http://localhost:3000/secrets.json")

    token = session[:token]

    @name = session[:name]

    response = Http.post("http://localhost:3000/users.json?token=#{token}")
    if response.code != 200
    end


  end


end

app/controllers/secrets_controller.rb
class SecretsController < ApplicationController

  def create
      @response = Http.post("http://localhost:3000/secrets.json", json: {secret:{title: params[:secret][:title], comment: params[:secret][:comment], created_at: params[:secret][:created_at]}})
  end

  def index
  end



end

app/controllers/session_controller.rb
class SessionController < ApplicationController
require 'http'

  def new
  end

  def create

    @http_response = Http.post("http://localhost:3000/auth.json", json: {email: params[:email], password: params[:password]})

    user = JSON.parse(@http_response)
    session[:name] = user["name"]
    session[:token] = user["token"]
    @name = session[:name] 

  end

  def destroy
    session[:name] = nil
    redirect_to root_path
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end


  def create
    @response = Http.post("http://localhost:3000/users.json", json: {user:{email: params[:user][:email], password: params[:user][:password], password_confirmation: params[:user][:password_confiration], name: params[:user][:name]}})


    user = JSON.parse(@response)
    session[:name] = user["name"]
    session[:token] = user["token"]

    @name = session[:name]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/secrets_helper.rb
module SecretsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SshhFrontend</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Playfair+Display:400italic' rel='stylesheet' type='text/css'>
</head>
<body>


<%= yield %>










</body>
</html>

app/views/pages/_links.html.erb
<% if !@name.nil? %>
  <button class="btn btn-primary btn-lg">
    <%= link_to "Log in", login_path, remote: true %>
  </button>
  <button class="btn btn-primary btn-lg">
    <%= link_to "Sign up", signup_path, remote: true %>
  </button>
<% else %>
  <button class="btn btn-primary btn-lg">
    <%= link_to "Log Out", logout_path, remote: true, method: delete %>
  </button>
  <button class="btn btn-primary btn-lg">
    <%= link_to "Add a Secret", "", remote: true%>
  </button>
<% end %>

app/views/pages/dashboard.html.erb
<div class="jumbotron">
  <h1> Secrets </h1>
  <em>  <p> Shhhh.... We promise not to tell.  </p>
    <p > Log in to discover and share your secrets. </p> </em>


      <% if @name.nil? %>
        <button class="btn btn-primary btn-lg">  <%= link_to "Log in", login_path, remote: true %>   </button>
        <button class="btn btn-primary btn-lg">  <%= link_to "Sign up", signup_path, remote: true %> </button>
      <% else %>
        <button class="btn btn-primary btn-lg"> <%= link_to "Log out", logout_path, method: :delete %> </button>
        <button class="btn btn-primary btn-lg"> <%= link_to "Add a Secret", secrets_path, remote: true %> </button>
      <%end%>
</div>

<div class="show_secret">
  <%= render partial: 'secrets/secrets' %>
</div>



<!--will need to take the links away and render the _links  -->







<div class="modal fade" id="super-wicked-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">
        replace
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/pages/dashboard.js.erb
$(".buttons").html("<%= j render partial: 'secrets'%> ");

app/views/secrets/_addsecret.html.erb
<%= simple_form_for :secret, remote: true do |f| %>
  <%= f.input :title %>
  <%= f.input :comment %>
  <%= f.submit %>
 <%end%>

app/views/secrets/_secrets.html.erb
<div class="container">
  <% if !@name.nil? %>
  <h1> Welcome <%= @name %> </h1>
  <br>
    <% @secrets.in_groups_of(3, false) do |secrets| %>
      <div class="row">
      <% secrets.each do |secret| %>
        <div class="col-sm-12  col-md-4" id="indiv-secret">
          <h3><%= secret["title"] %></h3>
          <br>
          <p><%= secret["comment"] %></p>
          <p> <em> Posted: <%= distance_of_time_in_words_to_now secret["created_at"] %> </em> </p>
        </div>
        <%end%>
      </div>
    <%end%>
  <%end%>
</div>

app/views/secrets/create.js.erb
<% if @response.code == 201 %>
  $("#super-wicked-modal").modal("hide");
    window.location = "/";

<% else %>
  $(".modal-body").html("<%= j render partial: 'addsecret'%> ");
  alert("Something went wrong. Check to see if you have a title and comment filled out. ");

<% end %>

app/views/secrets/index.js.erb
$("#super-wicked-modal .modal-body").html("<%= j render partial: 'addsecret'%> ");
$("#super-wicked-modal").modal("show");

app/views/session/_loginform.html.erb
<%= form_tag auth_path(@user), remote: true, method: :post do %>


  <div>
    <%= label_tag :email %>
    <%= text_field_tag :email, params[:email], class: "form-control" %>
    <br>
  </div>

  <div>
    <%= label_tag :password %>
    <%= password_field_tag :password, "", class: "form-control"%>
    <br>
  </div>

  <div>
    <%= submit_tag "Log In", class: "btn btn-primary btn-lg" %>
    <br>
    <br>
  </div>
<% end %>

app/views/session/create.js.erb
<% if @http_response.code == 201 %>
  $("#super-wicked-modal").modal("hide");
    window.location = "/";

  //  partial with the links to sign in
<% else %>
  alert("Something went wrong. Check to see if your username and password are correct. ");
  $("#super-wicked-modal .modal-body").html("<%= j render partial: 'loginform'%> ");
  <% end %>

app/views/session/new.js.erb
$("#super-wicked-modal .modal-body").html("<%= j render partial: 'loginform'%> ");
$("#super-wicked-modal").modal("show");

app/views/users/_signupform.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= simple_form_for :user, remote: true do |f| %>
      <%= f.input :name %>
      <%= f.input :email %>
      <%= f.input :password %>
      <%= f.input :password_confirmation %>
      <%= f.submit  %>
    <% end %>
  </div>
</div>

app/views/users/create.js.erb
<% if @response.code == 201 %>
// do i need to add the ruby logic here???
  $("#super-wicked-modal").modal("hide");
  window.location = "/";


  //  partial with the links to sign in
<% else %>
  $("#super-wicked-modal .modal-body").html("<%= j render partial: 'signupform'%> ");
  $("super-wicked-modal").modal("show");
<% end %>

app/views/users/new.js.erb
$("#super-wicked-modal .modal-body").html("<%= j render partial: 'signupform'%> ");
$("#super-wicked-modal").modal("show");